version: '3.8'
services:
  product-api:
    image: product-api:latest
    build:
      context: ./cmd/product
      dockerfile: Dockerfile
    ports:
      - '50051:50051'
    networks:
      - backend

  users-api:
    image: users-api:latest
    build:
      context: ./cmd/users
      dockerfile: Dockerfile
    ports:
      - '50052:50052'
    networks:
      - backend

  nginx:
    build: ./api-gateway
    restart: on-failure
    ports:
      - '80:80'
    depends_on:
      - product-api
      - users-api
    networks:
      - backend

networks:
  backend:
    driver: bridge
